version: "3"
services:
  app:
    build: .
    container_name: yml_generator
    hostname: yml-backend
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app
    tty: true
    networks:
      - yml-generator

networks:
  yml-generator:
    external: true